
package com.mangelt.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DescriptionNote", targetNamespace = "http://www.example.org/DescriptionNote/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DescriptionNote {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.mangelt.test.Note
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/DescriptionNote/NewOperation")
    @WebResult(name = "note", targetNamespace = "http://www.example.org/DescriptionNote/", partName = "parameters")
    public Note newOperation(
        @WebParam(name = "employee", targetNamespace = "http://www.example.org/DescriptionNote/", partName = "parameters")
        Employee parameters);

}
