
package com.mangelt.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DescriptionNote", targetNamespace = "http://www.example.org/DescriptionNote/", wsdlLocation = "file:/C:/Users/vn0x53q/workspaceKepler/personaservice/personaservice-api/src/main/resources/DescriptionNote.wsdl")
public class DescriptionNote_Service
    extends Service
{

    private final static URL DESCRIPTIONNOTE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.mangelt.test.DescriptionNote_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.mangelt.test.DescriptionNote_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/vn0x53q/workspaceKepler/personaservice/personaservice-api/src/main/resources/DescriptionNote.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/vn0x53q/workspaceKepler/personaservice/personaservice-api/src/main/resources/DescriptionNote.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DESCRIPTIONNOTE_WSDL_LOCATION = url;
    }

    public DescriptionNote_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DescriptionNote_Service() {
        super(DESCRIPTIONNOTE_WSDL_LOCATION, new QName("http://www.example.org/DescriptionNote/", "DescriptionNote"));
    }

    /**
     * 
     * @return
     *     returns DescriptionNote
     */
    @WebEndpoint(name = "DescriptionNoteSOAP")
    public DescriptionNote getDescriptionNoteSOAP() {
        return super.getPort(new QName("http://www.example.org/DescriptionNote/", "DescriptionNoteSOAP"), DescriptionNote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DescriptionNote
     */
    @WebEndpoint(name = "DescriptionNoteSOAP")
    public DescriptionNote getDescriptionNoteSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/DescriptionNote/", "DescriptionNoteSOAP"), DescriptionNote.class, features);
    }

}
